name: test

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - '.github/workflows/test.yml'
      - '.github/workflows/shellcheck.yml'
      - '.github/workflows/whisper_test.yml'
      - '.github/workflows/tests/**'

jobs:
  shellcheck:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/shellcheck.yml

  whisper_test:
    if: github.repository_owner == 'hwdsl2'
    uses: ./.github/workflows/whisper_test.yml
